
esp32_ble_beacon:
  type: IBEACON
  uuid: "8f1d2a60-4c3b-4e91-9a77-2b5c6d8e0f13"
  major: 1
  minor: 1
  min_interval: 100ms
  max_interval: 100ms
  measured_power: -59
  tx_power: 3dBm


sensor:
  - platform: debug
    free:
      name: "Free heap"
    loop_time:
      name: "Loop time"

